// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("bs-platform/lib/js/js_json.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function key(key$1, input) {
  return Promise.resolve(Js_primitive.undefined_to_opt(input[key$1]));
}

function path(_list, _input) {
  while(true) {
    var input = _input;
    var list = _list;
    if (list) {
      var xs = list[1];
      var key = list[0];
      if (xs) {
        var match = input[key];
        if (match !== undefined) {
          var match$1 = Js_json.classify(match);
          if (typeof match$1 === "number" || match$1.tag !== 2) {
            return Promise.resolve(/* None */0);
          } else {
            _input = match$1[0];
            _list = xs;
            continue ;
          }
        } else {
          return Promise.resolve(/* None */0);
        }
      } else {
        return Promise.resolve(Js_primitive.undefined_to_opt(input[key]));
      }
    } else {
      return Pervasives.failwith("Path must have at least one item");
    }
  };
}

exports.key = key;
exports.path = path;
/* No side effect */
