// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function unwrap(param) {
  if (param) {
    var match = param[0];
    if (match) {
      return /* Some */[match[0]];
    } else {
      return /* None */0;
    }
  } else {
    return /* None */0;
  }
}

exports.unwrap = unwrap;
/* No side effect */
