// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function make(fn) {
  return (function (maybe, _) {
            return Promise.resolve(maybe !== undefined ? Curry._1(fn, Js_primitive.valFromOption(maybe)) : undefined);
          });
}

function makeClassified(fn) {
  return make((function (json) {
                return Curry._1(fn, Js_json.classify(json));
              }));
}

exports.make = make;
exports.makeClassified = makeClassified;
/* No side effect */
