// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function make(fn) {
  return (function (maybe, param) {
            return Promise.resolve(maybe !== undefined ? Curry._1(fn, Caml_option.valFromOption(maybe)) : undefined);
          });
}

function makeClassified(fn) {
  return make(function (json) {
              return Curry._1(fn, Js_json.classify(json));
            });
}

exports.make = make;
exports.makeClassified = makeClassified;
/* No side effect */
