// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function unwrap(param) {
  if (param !== undefined) {
    var match = Js_primitive.valFromOption(param);
    if (match !== undefined) {
      return Js_primitive.some(Js_primitive.valFromOption(match));
    } else {
      return undefined;
    }
  }
  
}

exports.unwrap = unwrap;
/* No side effect */
