// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function unwrap(param) {
  if (param === undefined) {
    return ;
  }
  var x = Caml_option.valFromOption(param);
  if (x !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(x));
  }
  
}

exports.unwrap = unwrap;
/* No side effect */
