// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_json = require("bs-platform/lib/js/js_json.js");

function make(fn) {
  return /* Some */[(function (maybe, _) {
              return Promise.resolve(maybe ? Curry._1(fn, maybe[0]) : /* None */0);
            })];
}

function makeClassified(fn) {
  return make((function (json) {
                return Curry._1(fn, Js_json.classify(json));
              }));
}

exports.make = make;
exports.makeClassified = makeClassified;
/* No side effect */
